class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzip1'
        self.TarMirrorCommand = 'tar1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cnlall1'
        self.ListCommand = 'list'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'user'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauth1'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stat'
        self.HelpCommand = 'hlp'
        self.LogCommand = 'log'
        self.SpeedCommand = 'test'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo1'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'

BotCommands = _BotCommands()
